find_path(EPOS_CMD_INCLUDE_DIR Definitions.h
  PATHS
    ENV EPOS_CMD_INCLUDE_DIR
    ${EPOS_CMD_INCLUDE_DIR}
    /opt
  PATH_SUFFIXES
    EposCmdLib_6.7.1.0/include
)

find_library(EPOS_CMD_LIBRARY
  NAMES
    EposCmd
  PATHS
    ENV EPOS_CMD_LIB_DIR
    ${EPOS_CMD_LIB_DIR}
    /opt
  PATH_SUFFIXES
    lib
)

mark_as_advanced(EPOS_CMD_INCLUDE_DIR EPOS_CMD_LIBRARY)
include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(EPOS_CMD
  REQUIRED_VARS
    EPOS_CMD_INCLUDE_DIR
    EPOS_CMD_LIBRARY
)

if(EPOS_CMD_FOUND AND NOT TARGET EPOS_CMD::EPOS_CMD)
  add_library(EPOS_CMD::EPOS_CMD UNKNOWN IMPORTED)
  set_target_properties(EPOS_CMD::EPOS_CMD PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
    IMPORTED_LOCATION "${EPOS_CMD_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${EPOS_CMD_INCLUDE_DIR}"
    )
endif()
