joy:
  ros__parameters:
    coalesce_interval_ms: 0.01
    
teleop_twist_joy_node:
  ros__parameters:
    joy_config: 'ps3'
    joy_dev: '/dev/input/js0'

    require_enable_button: false # コントローラ有効化ボタン default:true
    enable_turbo_button: 7  # ターボモードボタン
    axis_linear:
      x: 1 # x軸のスティック位置の割り振り
    scale_linear:
      x: 0.7 
    scale_linear_turbo:
      x: 1.5 

    axis_angular:
      yaw: 3  # yaw軸のスティック位置の割り振り
    scale_angular:
      yaw: -0.4
    scale_angular_turbo:
      yaw: -1.0