joy_raw_node:
  ros__parameters:
    coalesce_interval: 0.01
    deadzone: 0.1
    
teleop_twist_joy_node:
  ros__parameters:
    joy_config: 'ps3'
    joy_dev: '/dev/input/js0'

    require_enable_button: false # コントローラ有効化ボタン default:true
    enable_turbo_button: 7  # ターボモードボタン
    axis_linear:
      x: 1 # x軸のスティック位置の割り振り
    scale_linear:
      x: 1.0
    scale_linear_turbo:
      x: 1.5 

    axis_angular:
      yaw: 3  # yaw軸のスティック位置の割り振り
    scale_angular:
      yaw: -1.0
    scale_angular_turbo:
      yaw: -1.0

flir_ax8_rtsp:
  ros__parameters:
    ip_addr: "192.168.1.22"
    encoding: "mpeg4"
    text_overlay: "off"
    rate_hz: 5