hand_camera/hand_camera:
  ros__parameters:
    video_device: "/dev/video_hand"
    framerate: 10.0
    io_method: "mmap"
    frame_id: "camera"
    pixel_format: "yuyv2rgb"
    image_width: 640
    image_height: 480
    camera_name: "hand_camera"
    .image_raw.jpeg_quality: 20

vision_front_camera/vision_front_camera:
  ros__parameters:
    video_device: "/dev/video_vision_front"
    framerate: 10.0
    io_method: "mmap"
    frame_id: "camera"
    pixel_format: "yuyv2rgb"
    image_width: 640
    image_height: 480
    camera_name: "vision_front_camera"
    .image_raw.jpeg_quality: 80

vision_rear_camera/vision_rear_camera:
  ros__parameters:
    video_device: "/dev/video_vision_rear"
    framerate: 10.0
    io_method: "mmap"
    frame_id: "camera"
    pixel_format: "yuyv2rgb"
    image_width: 640
    image_height: 480
    camera_name: "vision_rear_camera"
    .image_raw.jpeg_quality: 10

fisheye_front_camera/fisheye_front_camera:
  ros__parameters:
    video_device: "/dev/video_fisheye_front"
    framerate: 10.0
    io_method: "mmap"
    frame_id: "camera"
    pixel_format: "yuyv2rgb"
    image_width: 640
    image_height: 480
    camera_name: "fisheye_front_camera"
    .image_raw.jpeg_quality: 10
