darknet_ros:
  ros__parameters:
    yolo_model:
      config_file:
        name: robocup-hazmat-label-train.cfg
      weight_file:
        name: robocup-hazmat-label-train-final.weights
      threshold:
        value: 0.3
      detection_classes:
        names:
          - explosives
          - blasting-agents
          - flammable-gas
          - non-flammable-gas
          - oxygen
          - fuel-oil
          - dangerous-when-wet
          - flammable-solid
          - spontaneously-combustible
          - oxidizer
          - organic-peroxide
          - inhalation-hazard
          - poison
          - radioactive
          - corrosive
