#!/bin/sh

cd "$(dirname "$0")"

sh ./install-apt-tools
sh ./install-epos-command-library

source ./install-aliases

replace ~/.bash_aliases ./bash_aliases bash_aliases ./bash-settings/aliases-teleop
replace ~/.bashrc ./bashrc bashrc ./bash-settings/bashrc-teleop