#!/bin/sh

cd "$(dirname "$0")"

echo "install udev rules for usb devices"
cp rules/99-cameras.rules /etc/udev/rules.d/99-cameras.rules
cp rules/99-dynamixel-device.rules /etc/udev/rules.d/99-dynamixel-device.rules