#!/bin/sh

cd "$(dirname "$0")"

sh ./install-apt-tools
sh ./install-epos-command-library
sh ./install-udev-rules

source ./install-aliases

replace ~/.bash_aliases ./bash_aliases bash_aliases ./bash-settings/aliases-bringup
replace ~/.bashrc ./bashrc bashrc ./bash-settings/bashrc-bringup