/**:
  ros__parameters:
    xfer_format: 0 # not custom
    multi_topic: 0
    data_src: 0
    publish_freq: 10.0 # Hz
    output_data_type: 0
    frame_id: "mid360"

    feature_extract_enable: false
    point_filter_num: 3
    max_iteration: 3
    filter_size_surf: 0.5
    filter_size_map: 0.5
    cube_side_length: 1000.0
    runtime_pos_log_enable: false
    map_file_path: "./map.pcd"

    common:
      lid_topic: "/livox/lidar"
      imu_topic: "/livox/imu"
      time_sync_en: false # ONLY turn on when external time synchronization is really not possible
      time_offset_lidar_to_imu:
        0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
        # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

scan_matcher:
  ros__parameters:
    global_frame_id: "map"
    robot_frame_id: "base_footprint"
    registration_method: "NDT"
    ndt_resolution: 0.5
    ndt_num_threads: 4
    gicp_corr_dist_threshold: 5.0
    trans_for_mapupdate: 1.0
    vg_size_for_input: 0.1
    vg_size_for_map: 0.1
    use_min_max_filter: true
    scan_min_range: 0.3
    scan_max_range: 10.0
    scan_period: 0.1
    map_publish_period: 15.0
    num_targeted_cloud: 20
    set_initial_pose: true
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_z: 0.0
    initial_pose_qx: 0.0
    initial_pose_qy: 0.0
    initial_pose_qz: 0.0
    initial_pose_qw: 1.0
    use_imu: false
    use_odom: false
    debug_flag: false

graph_based_slam:
  ros__parameters:
    registration_method: "NDT"
    ndt_resolution: 0.2
    ndt_num_threads: 4
    voxel_leaf_size: 0.01
    loop_detection_period: 1000
    threshold_loop_closure_score: 0.7
    distance_loop_closure: 10.0
    range_of_searching_loop_closure: 2.0
    search_submap_num: 2
    num_adjacent_pose_cnstraints: 5
    use_save_map_in_loop: true
    debug_flag: true
