epos:
  ros__parameters:
    device_name: "EPOS4"
    protocol: "MAXON SERIAL V2"
    interface: "USB"
    portname: "USB0"

    use_sub_device: true
    sub_device_name: "EPOS4"
    sub_device_protocol: "CANopen"

    auto_enable: true
    dataout_freq: 30

    motor_id: [6]
    motor_id_on_sub: [2, 3, 4, 5, 7]

r5sr_crawler_control:
  ros__parameters:
    wheel_diameter: 0.14
    wheel_base: 0.25

rplidar:
  ros__parameters:
    serial_port: "/dev/ttyUSB-RPLiDARS1"
    serial_baudrate: 256000
    frame_id: "rplidar_link"
    inverted: false
    angle_compensate: true
