# Default initial positions for the robot arm's ros2_control fake system
initial_positions:
  body1_joint: 0.0
  body2_joint: 0.0
  body3_joint: 0.0
  body4_joint: 0.0
  body5_joint: 0.0
  body6_joint: 0.0
  vision_arm_body1_joint: 0.0
  vision_arm_body2_joint: 0.0
  vision_arm_body3_joint: 0.0