# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - main_arm_controller
    - sub_arm_controller

  main_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - body1_joint
      - body2_joint
      - body3_joint
      - body4_joint
      - body5_joint
      - body6_joint
  sub_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - vision_arm_body1_joint
      - vision_arm_body2_joint
      - vision_arm_body3_joint