# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    main_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    sub_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

main_arm_controller:
  ros__parameters:
    joints:
      - body1_joint
      - body2_joint
      - body3_joint
      - body4_joint
      - body5_joint
      - body6_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
sub_arm_controller:
  ros__parameters:
    joints:
      - vision_arm_body1_joint
      - vision_arm_body2_joint
      - vision_arm_body3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity