#!/bin/sh

echo "install tools"
sudo apt update -qq
sudo apt install -y -qq python3-vcstool
sudo apt-get install openssh-server
sudo apt-get install xorg
sudo apt install git-flow

echo "install success"